"""
Management command: python manage.py seed_demo

Creates demo users and fake predictions so the app looks populated
during a demo even when the FastAPI backend is not running.
"""
import os
import random
from datetime import timedelta
from io import BytesIO

from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand
from django.utils import timezone

try:
    from PIL import Image as PILImage
    HAS_PILLOW = True
except ImportError:
    HAS_PILLOW = False

from core.models import Prediction

User = get_user_model()

GRADE_LABELS = ['No DR', 'Mild NPDR', 'Moderate NPDR', 'Severe NPDR', 'Proliferative DR']
GRADE_COLORS = [(80, 200, 80), (160, 210, 50), (255, 200, 50), (255, 140, 40), (255, 90, 90)]

SAMPLE_PROBS = [
    [0.88, 0.07, 0.03, 0.01, 0.01],
    [0.05, 0.82, 0.09, 0.03, 0.01],
    [0.02, 0.06, 0.84, 0.06, 0.02],
    [0.01, 0.03, 0.08, 0.79, 0.09],
    [0.01, 0.02, 0.05, 0.10, 0.82],
]


class Command(BaseCommand):
    help = 'Seed demo users and sample predictions for demonstration purposes.'

    def handle(self, *args, **options):
        self._create_users()
        self._create_predictions()
        self.stdout.write(self.style.SUCCESS('Demo data seeded successfully.'))

    def _create_users(self):
        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser(
                username='admin',
                email='admin@retinagrade.local',
                password='admin123',
                role='admin',
                institution='RetinaGrade Demo',
            )
            self.stdout.write('  Created: admin / admin123  (role: admin)')
        else:
            self.stdout.write('  User "admin" already exists — skipped.')

        if not User.objects.filter(username='clinician').exists():
            User.objects.create_user(
                username='clinician',
                email='clinician@retinagrade.local',
                password='clinic123',
                first_name='Dr. Alex',
                last_name='Demo',
                role='clinician',
                institution='City Eye Hospital',
            )
            self.stdout.write('  Created: clinician / clinic123  (role: clinician)')
        else:
            self.stdout.write('  User "clinician" already exists — skipped.')

    def _create_predictions(self):
        user = User.objects.get(username='clinician')
        if Prediction.objects.filter(user=user).count() >= 5:
            self.stdout.write('  Predictions already exist for "clinician" — skipped.')
            return

        for i in range(5):
            grade = i
            probs = SAMPLE_PROBS[grade]
            confidence = max(probs)
            img_file = self._make_fake_image(grade)
            created_at = timezone.now() - timedelta(days=random.randint(0, 14))

            pred = Prediction(
                user=user,
                grade=grade,
                label=GRADE_LABELS[grade],
                confidence=confidence,
                probabilities=probs,
                grad_cam_image='',
                notes='Demo prediction — generated by seed_demo command.',
                created_at=created_at,
            )
            pred.image.save(f'demo_grade{grade}.png', img_file, save=False)
            pred.save()
            self.stdout.write(f'  Created prediction grade {grade}: {GRADE_LABELS[grade]}')

    def _make_fake_image(self, grade: int) -> ContentFile:
        if not HAS_PILLOW:
            return ContentFile(b'\x89PNG\r\n\x1a\n', name='demo.png')

        color = GRADE_COLORS[grade]
        img = PILImage.new('RGB', (224, 224), color=(10, 10, 20))
        # Draw a simple circular gradient-ish pattern
        import math
        cx, cy = 112, 112
        pixels = img.load()
        for y in range(224):
            for x in range(224):
                dist = math.sqrt((x - cx) ** 2 + (y - cy) ** 2)
                factor = max(0, 1 - dist / 100)
                pixels[x, y] = (
                    int(color[0] * factor + 10 * (1 - factor)),
                    int(color[1] * factor + 10 * (1 - factor)),
                    int(color[2] * factor + 10 * (1 - factor)),
                )

        buf = BytesIO()
        img.save(buf, format='PNG')
        buf.seek(0)
        return ContentFile(buf.read(), name=f'demo_grade{grade}.png')
